// Generated from web/tokens.json by npm run build:web. Do not edit.
export declare const version: "0.1.8"
export declare const brands: readonly ["zane","opcorbit"]
export type WebBrand = (typeof brands)[number]
export declare const themes: readonly ["dark", "light"]
export type WebTheme = (typeof themes)[number]
export declare const tokens: {
  readonly "base": {
    readonly "--xui-color-text-on-image": "#FFFFFF"
    readonly "--xui-font-cjk": "\"Noto Sans SC\",\"Noto Sans CJK SC\",\"PingFang SC\",\"Hiragino Sans GB\",\"Microsoft YaHei\",sans-serif"
    readonly "--xui-type-display-xl": "clamp(52px,7.2vw,112px)"
    readonly "--xui-type-display-lg": "clamp(40px,5vw,76px)"
    readonly "--xui-type-heading-lg": "clamp(30px,3.2vw,48px)"
    readonly "--xui-type-heading-md": "clamp(24px,2.2vw,32px)"
    readonly "--xui-type-body-lg": "clamp(18px,1.4vw,21px)"
    readonly "--xui-type-body-md": "17px"
    readonly "--xui-type-body-sm": "15px"
    readonly "--xui-type-label": "13px"
    readonly "--xui-type-line-height-display": "1.05"
    readonly "--xui-type-line-height-heading": "1.15"
    readonly "--xui-type-line-height-body": "1.55"
    readonly "--xui-type-tracking-label": ".06em"
    readonly "--xui-type-tracking-heading": ".01em"
    readonly "--xui-type-tracking-body": "0"
    readonly "--xui-type-button": "var(--xui-type-body-sm)"
    readonly "--xui-type-nav": "var(--xui-type-body-sm)"
    readonly "--xui-type-wordmark": "var(--xui-type-body-lg)"
    readonly "--xui-type-menu-row": "var(--xui-type-heading-lg)"
    readonly "--xui-type-footer": "var(--xui-type-body-sm)"
    readonly "--xui-type-pill": "var(--xui-type-label)"
    readonly "--xui-type-release": "var(--xui-type-body-sm)"
    readonly "--xui-space-1": "4px"
    readonly "--xui-space-2": "8px"
    readonly "--xui-space-3": "12px"
    readonly "--xui-space-4": "16px"
    readonly "--xui-space-5": "24px"
    readonly "--xui-space-6": "32px"
    readonly "--xui-space-7": "48px"
    readonly "--xui-space-8": "64px"
    readonly "--xui-space-9": "96px"
    readonly "--xui-space-10": "128px"
    readonly "--xui-space-11": "160px"
    readonly "--xui-radius-none": "0"
    readonly "--xui-radius-sm": "2px"
    readonly "--xui-radius-md": "4px"
    readonly "--xui-radius-pill": "999px"
    readonly "--xui-motion-duration-fast": "150ms"
    readonly "--xui-motion-duration-base": "250ms"
    readonly "--xui-motion-duration-slow": "600ms"
    readonly "--xui-motion-easing-standard": "cubic-bezier(.2,0,0,1)"
    readonly "--xui-layout-max": "1280px"
    readonly "--xui-layout-margin": "64px"
    readonly "--xui-layout-gutter": "24px"
    readonly "--xui-layout-nav-height": "64px"
    readonly "--xui-size-control-min": "44px"
    readonly "--xui-size-button": "48px"
    readonly "--xui-size-menu-row": "64px"
    readonly "--xui-focus-width": "2px"
    readonly "--xui-border-width-subtle": "1px"
    readonly "--xui-border-width-strong": "1px"
    readonly "--xui-border-width-accent": "2px"
    readonly "--xui-border-width-emphasis": "3px"
    readonly "--xui-focus-offset": "3px"
    readonly "--xui-safe-top": "env(safe-area-inset-top,0px)"
    readonly "--xui-safe-right": "env(safe-area-inset-right,0px)"
    readonly "--xui-safe-bottom": "env(safe-area-inset-bottom,0px)"
    readonly "--xui-safe-left": "env(safe-area-inset-left,0px)"
  }
  readonly "scopes": readonly [{
    readonly "selector": ":root:lang(zh)"
    readonly "media": null
    readonly "declarations": {
      readonly "--xui-font-display": "var(--xui-font-cjk)"
      readonly "--xui-type-case-heading": "none"
      readonly "--xui-type-tracking-label": "0"
      readonly "--xui-type-tracking-heading": "0"
      readonly "--xui-type-line-height-display": "1.2"
      readonly "--xui-type-line-height-heading": "1.3"
      readonly "--xui-type-line-height-body": "1.75"
    }
  }, {
    readonly "selector": ":root"
    readonly "media": "(max-width:1023px)"
    readonly "declarations": {
      readonly "--xui-layout-margin": "32px"
    }
  }, {
    readonly "selector": ":root"
    readonly "media": "(max-width:767px)"
    readonly "declarations": {
      readonly "--xui-layout-margin": "20px"
      readonly "--xui-layout-nav-height": "56px"
    }
  }, {
    readonly "selector": ":root"
    readonly "media": "(max-width:479px)"
    readonly "declarations": {
      readonly "--xui-type-body-md": "16px"
    }
  }, {
    readonly "selector": ":root"
    readonly "media": "(prefers-reduced-motion:reduce)"
    readonly "declarations": {
      readonly "--xui-motion-duration-fast": "0ms"
      readonly "--xui-motion-duration-base": "0ms"
      readonly "--xui-motion-duration-slow": "0ms"
    }
  }]
  readonly "color": {
    readonly "dark": {
      readonly "--xui-color-bg-base": "#000000"
      readonly "--xui-color-bg-raised": "#000000"
      readonly "--xui-color-bg-inverse": "#FFFFFF"
      readonly "--xui-color-text-primary": "#FFFFFF"
      readonly "--xui-color-text-secondary": "#B3B3B3"
      readonly "--xui-color-text-tertiary": "#8F8F8F"
      readonly "--xui-color-text-inverse": "#000000"
      readonly "--xui-color-border-subtle": "#5E5E5E"
      readonly "--xui-color-border-strong": "#767676"
      readonly "--xui-color-accent-text": "#FFFFFF"
      readonly "--xui-color-accent-fill": "#FFFFFF"
      readonly "--xui-color-accent-on": "#000000"
      readonly "--xui-color-action-fill": "#FFFFFF"
      readonly "--xui-color-action-on": "#000000"
      readonly "--xui-color-highlight": "transparent"
      readonly "--xui-color-avatar-ring": "#5E5E5E"
      readonly "--xui-color-avatar-halo": "transparent"
      readonly "--xui-color-accent-strong": "var(--xui-color-accent-text)"
      readonly "--xui-color-focus-ring": "var(--xui-color-text-primary)"
    }
    readonly "light": {
      readonly "--xui-color-bg-base": "#FFFFFF"
      readonly "--xui-color-bg-raised": "#FFFFFF"
      readonly "--xui-color-bg-inverse": "#000000"
      readonly "--xui-color-text-primary": "#000000"
      readonly "--xui-color-text-secondary": "#525252"
      readonly "--xui-color-text-tertiary": "#6B6B6B"
      readonly "--xui-color-text-inverse": "#FFFFFF"
      readonly "--xui-color-border-subtle": "#8F8F8F"
      readonly "--xui-color-border-strong": "#767676"
      readonly "--xui-color-accent-text": "#000000"
      readonly "--xui-color-accent-fill": "#000000"
      readonly "--xui-color-accent-on": "#FFFFFF"
      readonly "--xui-color-action-fill": "#000000"
      readonly "--xui-color-action-on": "#FFFFFF"
      readonly "--xui-color-highlight": "transparent"
      readonly "--xui-color-avatar-ring": "#8F8F8F"
      readonly "--xui-color-avatar-halo": "transparent"
      readonly "--xui-color-accent-strong": "var(--xui-color-accent-text)"
      readonly "--xui-color-focus-ring": "var(--xui-color-text-primary)"
    }
  }
  readonly "brands": {
    readonly "zane": {
      readonly "shape": {
        readonly "--xui-font-display": "\"Barlow Condensed\",var(--xui-font-cjk)"
        readonly "--xui-font-body": "\"Inter\",system-ui,var(--xui-font-cjk)"
        readonly "--xui-font-mono": "\"JetBrains Mono\",ui-monospace,monospace"
        readonly "--xui-font-wordmark": "\"Barlow Condensed\",sans-serif"
        readonly "--xui-type-case-heading": "uppercase"
        readonly "--xui-radius-component": "2px"
        readonly "--xui-shadow-overlay": "none"
      }
      readonly "dark": {
        readonly "--xui-font-display": "\"Barlow Condensed\",var(--xui-font-cjk)"
        readonly "--xui-font-body": "\"Inter\",system-ui,var(--xui-font-cjk)"
        readonly "--xui-font-mono": "\"JetBrains Mono\",ui-monospace,monospace"
        readonly "--xui-font-wordmark": "\"Barlow Condensed\",sans-serif"
        readonly "--xui-type-case-heading": "uppercase"
        readonly "--xui-radius-component": "2px"
        readonly "--xui-shadow-overlay": "none"
        readonly "--xui-color-bg-base": "#000000"
        readonly "--xui-color-bg-raised": "#000000"
        readonly "--xui-color-bg-inverse": "#FFFFFF"
        readonly "--xui-color-text-primary": "#FFFFFF"
        readonly "--xui-color-text-secondary": "#B3B3B3"
        readonly "--xui-color-text-tertiary": "#8F8F8F"
        readonly "--xui-color-text-inverse": "#000000"
        readonly "--xui-color-border-subtle": "#5E5E5E"
        readonly "--xui-color-border-strong": "#767676"
        readonly "--xui-color-accent-text": "#FFFFFF"
        readonly "--xui-color-accent-fill": "#FFFFFF"
        readonly "--xui-color-accent-on": "#000000"
        readonly "--xui-color-action-fill": "#FFFFFF"
        readonly "--xui-color-action-on": "#000000"
        readonly "--xui-color-highlight": "transparent"
        readonly "--xui-color-avatar-ring": "#5E5E5E"
        readonly "--xui-color-avatar-halo": "transparent"
        readonly "--xui-color-accent-strong": "var(--xui-color-accent-text)"
        readonly "--xui-color-focus-ring": "var(--xui-color-text-primary)"
      }
      readonly "light": {
        readonly "--xui-color-bg-base": "#FFFFFF"
        readonly "--xui-color-bg-raised": "#FFFFFF"
        readonly "--xui-color-bg-inverse": "#000000"
        readonly "--xui-color-text-primary": "#000000"
        readonly "--xui-color-text-secondary": "#525252"
        readonly "--xui-color-text-tertiary": "#6B6B6B"
        readonly "--xui-color-text-inverse": "#FFFFFF"
        readonly "--xui-color-border-subtle": "#8F8F8F"
        readonly "--xui-color-border-strong": "#767676"
        readonly "--xui-color-accent-text": "#000000"
        readonly "--xui-color-accent-fill": "#000000"
        readonly "--xui-color-accent-on": "#FFFFFF"
        readonly "--xui-color-action-fill": "#000000"
        readonly "--xui-color-action-on": "#FFFFFF"
        readonly "--xui-color-highlight": "transparent"
        readonly "--xui-color-avatar-ring": "#8F8F8F"
        readonly "--xui-color-avatar-halo": "transparent"
        readonly "--xui-color-accent-strong": "var(--xui-color-accent-text)"
        readonly "--xui-color-focus-ring": "var(--xui-color-text-primary)"
      }
      readonly "onImage": {
        readonly "--xui-color-bg-base": "#000000"
        readonly "--xui-color-bg-raised": "#000000"
        readonly "--xui-color-bg-inverse": "#FFFFFF"
        readonly "--xui-color-text-primary": "#FFFFFF"
        readonly "--xui-color-text-secondary": "#B3B3B3"
        readonly "--xui-color-text-tertiary": "#8F8F8F"
        readonly "--xui-color-text-inverse": "#000000"
        readonly "--xui-color-border-subtle": "#5E5E5E"
        readonly "--xui-color-border-strong": "#767676"
        readonly "--xui-color-accent-text": "#FFFFFF"
        readonly "--xui-color-accent-fill": "#FFFFFF"
        readonly "--xui-color-accent-on": "#000000"
        readonly "--xui-color-action-fill": "#FFFFFF"
        readonly "--xui-color-action-on": "#000000"
        readonly "--xui-color-highlight": "transparent"
        readonly "--xui-color-avatar-ring": "#5E5E5E"
        readonly "--xui-color-avatar-halo": "transparent"
        readonly "--xui-color-accent-strong": "var(--xui-color-accent-text)"
        readonly "--xui-color-focus-ring": "var(--xui-color-text-primary)"
      }
    }
    readonly "opcorbit": {
      readonly "shape": {
        readonly "--xui-font-display": "\"Geist\",var(--xui-font-cjk)"
        readonly "--xui-font-body": "\"Geist\",system-ui,var(--xui-font-cjk)"
        readonly "--xui-font-mono": "\"Geist Mono\",ui-monospace,monospace"
        readonly "--xui-font-wordmark": "\"Geist\",sans-serif"
        readonly "--xui-type-case-heading": "none"
        readonly "--xui-radius-component": "4px"
        readonly "--xui-shadow-overlay": "none"
      }
      readonly "dark": {
        readonly "--xui-font-display": "\"Geist\",var(--xui-font-cjk)"
        readonly "--xui-font-body": "\"Geist\",system-ui,var(--xui-font-cjk)"
        readonly "--xui-font-mono": "\"Geist Mono\",ui-monospace,monospace"
        readonly "--xui-font-wordmark": "\"Geist\",sans-serif"
        readonly "--xui-type-case-heading": "none"
        readonly "--xui-radius-component": "4px"
        readonly "--xui-shadow-overlay": "none"
        readonly "--xui-color-bg-base": "#000000"
        readonly "--xui-color-bg-raised": "#000000"
        readonly "--xui-color-bg-inverse": "#FFFFFF"
        readonly "--xui-color-text-primary": "#FFFFFF"
        readonly "--xui-color-text-secondary": "#B3B3B3"
        readonly "--xui-color-text-tertiary": "#8F8F8F"
        readonly "--xui-color-text-inverse": "#000000"
        readonly "--xui-color-border-subtle": "#5E5E5E"
        readonly "--xui-color-border-strong": "#767676"
        readonly "--xui-color-accent-text": "#FFFFFF"
        readonly "--xui-color-accent-fill": "#FFFFFF"
        readonly "--xui-color-accent-on": "#000000"
        readonly "--xui-color-action-fill": "#FFFFFF"
        readonly "--xui-color-action-on": "#000000"
        readonly "--xui-color-highlight": "transparent"
        readonly "--xui-color-avatar-ring": "#5E5E5E"
        readonly "--xui-color-avatar-halo": "transparent"
        readonly "--xui-color-accent-strong": "var(--xui-color-accent-text)"
        readonly "--xui-color-focus-ring": "var(--xui-color-text-primary)"
      }
      readonly "light": {
        readonly "--xui-color-bg-base": "#FFFFFF"
        readonly "--xui-color-bg-raised": "#FFFFFF"
        readonly "--xui-color-bg-inverse": "#000000"
        readonly "--xui-color-text-primary": "#000000"
        readonly "--xui-color-text-secondary": "#525252"
        readonly "--xui-color-text-tertiary": "#6B6B6B"
        readonly "--xui-color-text-inverse": "#FFFFFF"
        readonly "--xui-color-border-subtle": "#8F8F8F"
        readonly "--xui-color-border-strong": "#767676"
        readonly "--xui-color-accent-text": "#000000"
        readonly "--xui-color-accent-fill": "#000000"
        readonly "--xui-color-accent-on": "#FFFFFF"
        readonly "--xui-color-action-fill": "#000000"
        readonly "--xui-color-action-on": "#FFFFFF"
        readonly "--xui-color-highlight": "transparent"
        readonly "--xui-color-avatar-ring": "#8F8F8F"
        readonly "--xui-color-avatar-halo": "transparent"
        readonly "--xui-color-accent-strong": "var(--xui-color-accent-text)"
        readonly "--xui-color-focus-ring": "var(--xui-color-text-primary)"
      }
      readonly "onImage": {
        readonly "--xui-color-bg-base": "#000000"
        readonly "--xui-color-bg-raised": "#000000"
        readonly "--xui-color-bg-inverse": "#FFFFFF"
        readonly "--xui-color-text-primary": "#FFFFFF"
        readonly "--xui-color-text-secondary": "#B3B3B3"
        readonly "--xui-color-text-tertiary": "#8F8F8F"
        readonly "--xui-color-text-inverse": "#000000"
        readonly "--xui-color-border-subtle": "#5E5E5E"
        readonly "--xui-color-border-strong": "#767676"
        readonly "--xui-color-accent-text": "#FFFFFF"
        readonly "--xui-color-accent-fill": "#FFFFFF"
        readonly "--xui-color-accent-on": "#000000"
        readonly "--xui-color-action-fill": "#FFFFFF"
        readonly "--xui-color-action-on": "#000000"
        readonly "--xui-color-highlight": "transparent"
        readonly "--xui-color-avatar-ring": "#5E5E5E"
        readonly "--xui-color-avatar-halo": "transparent"
        readonly "--xui-color-accent-strong": "var(--xui-color-accent-text)"
        readonly "--xui-color-focus-ring": "var(--xui-color-text-primary)"
      }
    }
  }
}
export type WebTokens = typeof tokens
